In [26]:
# OLIST_ORDERS TABLE CLEANING -->

import pandas as pd
import numpy as np

In [27]:
orders = pd.read_csv("olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [28]:
orders.info() # To check information of the dataset including - 
# which columns are 'objects' - 
# which column have missing values - 
# Dtype is right or wrong?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [29]:
orders.shape

(99441, 8)

In [30]:
date_cols = [ # Here we have taken list of strings as date_cols where we have approximately 
    # 5 attributes which we need to convert to datetime.
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col], errors="coerce") # to_datetime() is a function in Pandas Library 
    # which is used to convert normal string(object) to datetime.
    # errors = "coerce" meaning removing error and replacing it with (NaT).

In [31]:
orders.isnull().sum() # Missing value analysis.

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [32]:
invalid_delivery = orders[ # Delivered date purchase se pehle to nahi?
    orders["order_delivered_customer_date"] <
    orders["order_purchase_timestamp"]
]

invalid_delivery.shape

(0, 8)

In [33]:
orders[ # Estimated date purchase se pehle to nahi?
orders["order_estimated_delivery_date"] < 
orders["order_purchase_timestamp"]
].shape

(0, 8)

In [34]:
orders["delivery_delay_days"] = ( # Raw data me ye column nahi hota
                                  # Business analysis ke liye banana padta hai.
    orders["order_delivered_customer_date"]
    - orders["order_estimated_delivery_date"]
).dt.days

In [35]:
orders_delivered = orders[
     orders["order_status"] == "delivered"
].copy() # Here copy() is very important because it avoids Pandas warning.

In [36]:
orders_delivered["delivery_delay_days"].describe() # Outliers sanity check.

count    96470.000000
mean       -11.875889
std         10.182105
min       -147.000000
25%        -17.000000
50%        -12.000000
75%         -7.000000
max        188.000000
Name: delivery_delay_days, dtype: float64

In [37]:
orders_delivered.to_csv(
    "clean_olist_orders.csv",
    index=False
) # Cleaned file bangayi.

In [25]:
# OLIST_CUSTOMERS TABLE CLEANING -->

In [38]:
import pandas as pd
import numpy as np

In [41]:
customers = pd.read_csv("olist_customers_dataset.csv")
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [42]:
customers.shape

(99441, 5)

In [44]:
customers.info() # Basically datatypes ki information deta hai.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [45]:
customers.head()
customers.describe(include="all")

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,274fa6071e5e17fe303b9748641082c8,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

In [49]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [50]:
customers.duplicated(subset = "customer_id").sum()

np.int64(0)

In [53]:
customers.duplicated(subset = "customer_unique_id").sum()

np.int64(3345)

In [55]:
customers["customer_city"] = customers["customer_city"].str.lower().str.strip()

In [57]:
customers["customer_state"] = customers["customer_state"].str.upper().str.strip()

In [58]:
customers["customer_zip_code_prefix"] = (
    customers["customer_zip_code_prefix"]
    .astype(str)
    .str.zfill(5)
)

In [59]:
customers["customer_state"].value_counts().head()
customers["customer_city"].nunique()

4119

In [62]:
customers.to_csv(
    "cleaned_olist_customers.csv",
    index=False
)

In [1]:
# OLIST_ORDER_ITEMS TABLE CLEANING -->

In [2]:
import pandas as pd
import numpy as np

In [4]:
order_items = pd.read_csv("olist_order_items_dataset.csv") # yahan hum data ko read karwa rahe hai/ load karwa rahe hai.

In [5]:
# shape pata karne ke liye (dimension pata chalengi) -->
order_items.shape

(112650, 7)

In [6]:
# information
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [7]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [9]:
order_items.describe() # isse pata chalta hai minimum value kitni hai, 
# maximum value kitni hai, 
# mean kya hai, 
# median kya hai, 
# standard deviation kya hai, 
# variance kya hai, 
# 25% kya hai, 
# 50% kya hai, 
# 75% kya hai.

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [10]:
# to check missing values
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [13]:
# to check full duplicate rows.
order_items.duplicated().sum()

np.int64(0)

In [14]:
order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

np.int64(0)

In [16]:
# shipping limit date ko string se datetime me convert karne zaruri hai in python.
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"], errors = "coerce")
order_items["shipping_limit_date"].isnull().sum()

np.int64(0)

In [17]:
(order_items["price"] < 0).sum()

np.int64(0)

In [18]:
(order_items["freight_value"] < 0).sum()

np.int64(0)

In [20]:
# outlier awareness (no removal yet)
order_items[["price", "freight_value"]].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [22]:
# feature creation (feature_engineering) >> "item_total_value" -->
order_items["item_total_value"] = (order_items["price"] + order_items["freight_value"])

In [23]:
order_items.to_csv(
    "clean_olist_order_items.csv",
    index=False
)

In [24]:
# OLIST_ORDER_PAYMENTS TABLE CLEANING -->

In [25]:
import pandas as pd
import numpy as np

In [26]:
order_payments = pd.read_csv("olist_order_payments_dataset.csv")

In [28]:
order_payments.shape

(103886, 5)

In [29]:
order_payments.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [30]:
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [31]:
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [32]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [33]:
order_payments.duplicated(
    subset=["order_id", "payment_sequential"]
).sum()

np.int64(0)

In [34]:
order_payments["payment_type"] = (order_payments["payment_type"].str.lower().str.strip())

In [35]:
order_payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [36]:
(order_payments["payment_value"] < 0).sum()

np.int64(0)

In [37]:
order_payments["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [40]:
order_payments["is_installment"] = (order_payments["payment_installments"] > 1)

In [41]:
order_payments.to_csv(
    "clean_olist_order_payments.csv",
    index=False
)

In [1]:
# OLIST_PRODUCTS TABLE CLEANING -->

In [2]:
import pandas as pd
import numpy as np

In [3]:
products = pd.read_csv("olist_products_dataset.csv")

In [4]:
products.shape

(32951, 9)

In [5]:
products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [6]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [7]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [8]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [10]:
products.duplicated(subset="product_id").sum()

np.int64(0)

In [11]:
products = products.drop_duplicates(subset="product_id")

In [12]:
num_cols = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

products[num_cols] = products[num_cols].apply(pd.to_numeric, errors="coerce")

In [13]:
# fixing logical inconsistencies
# negative value --> NaN
# zero dimensions --> NaN.
products[num_cols] = products[num_cols].where(products[num_cols] >= 0, np.nan)

In [15]:
dimension_cols = [
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

products[dimension_cols] = products[dimension_cols].replace(0, np.nan)

In [17]:
products["product_category_name"] = products["product_category_name"].astype("string")

In [18]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [19]:
products.to_csv("clean_olist_products.csv", index=False)

In [20]:
# OLIST_ORDER_REVIEWS TABLE CLEANING -->

In [21]:
import pandas as pd
import numpy as np

In [22]:
order_reviews = pd.read_csv("olist_order_reviews.csv")

In [23]:
order_reviews.shape

(99224, 7)

In [24]:
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [25]:
order_reviews.describe()

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [26]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,18/01/2018 00:00,18/01/2018 21:46
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,10/03/2018 00:00,11/03/2018 03:05
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,17/02/2018 00:00,18/02/2018 14:36
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,21/04/2017 00:00,21/04/2017 22:02
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,01/03/2018 00:00,02/03/2018 10:26

In [30]:
order_reviews.duplicated(subset = "review_id").sum()

np.int64(0)

In [31]:
order_reviews = order_reviews.drop_duplicates(subset = "review_id")

In [32]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       86891
review_comment_message     57742
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [34]:
order_reviews["review_score"] = pd.to_numeric(order_reviews["review_score"], errors = "coerce")

In [36]:
order_reviews.loc[~order_reviews["review_score"].between(1, 5), "review_score"] = np.nan

In [38]:
date_cols = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in date_cols:
    order_reviews[col] = pd.to_datetime(order_reviews[col], errors="coerce")

C:\Users\pc\AppData\Local\Temp\ipykernel_19564\3789858073.py:7: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  order_reviews[col] = pd.to_datetime(order_reviews[col], errors="coerce")
C:\Users\pc\AppData\Local\Temp\ipykernel_19564\3789858073.py:7: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  order_reviews[col] = pd.to_datetime(order_reviews[col], errors="coerce")

In [40]:
text_cols = ["review_comment_title", "review_comment_message"]

order_reviews[text_cols] = order_reviews[text_cols].astype("string")

In [42]:
mask = order_reviews["review_answer_timestamp"] < order_reviews["review_creation_date"]
order_reviews.loc[mask, "review_answer_timestamp"] = pd.NaT

In [43]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       86891
review_comment_message     57742
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [45]:
order_reviews.to_csv("clean_olist_order_reviews.csv", index=False)

In [46]:
# OLIST_SELLERS TABLE CLEANING -->

In [47]:
import pandas as pd
import numpy as np

In [48]:
sellers = pd.read_csv("olist_sellers_dataset.csv")

In [49]:
sellers.shape

(3095, 4)

In [50]:
sellers.describe()

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

In [51]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [52]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [55]:
sellers.duplicated(subset = "seller_id").sum()

np.int64(0)

In [54]:
sellers = sellers.drop_duplicates(subset = "seller_id")

In [56]:
sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [57]:
sellers["seller_zip_code_prefix"] = pd.to_numeric(sellers["seller_zip_code_prefix"], errors = "coerce")

In [58]:
text_cols = ["seller_city", "seller_state"]
sellers[text_cols] = sellers[text_cols].astype("string")

sellers["seller_city"] = sellers["seller_city"].str.lower().str.strip()
sellers["seller_state"] = sellers["seller_state"].str.upper().str.strip()

In [59]:
sellers.loc[sellers["seller_state"].str.len() != 2, "seller_state"] = pd.NA

In [60]:
sellers.loc[
    sellers["seller_zip_code_prefix"].astype("Int64").astype(str).str.len() != 5,
    "seller_zip_code_prefix"
] = pd.NA

In [61]:
sellers.isna().sum()

seller_id                    0
seller_zip_code_prefix    1027
seller_city                  0
seller_state                 0
dtype: int64

In [62]:
sellers.to_csv("clean_olist_sellers.csv", index = False)

In [66]:
# PRODUCT_CATEGORY_NAME_TRANSLATION TABLE CLEANING -->

In [74]:
import pandas as pd
import numpy as np

In [75]:
product_category = pd.read_csv("product_category_name_translation.csv")

In [76]:
product_category.shape

(71, 2)

In [77]:
product_category.describe()

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [78]:
product_category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [79]:
product_category.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [82]:
product_category.duplicated().sum()

np.int64(0)

In [83]:
product_category.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [84]:
product_category = product_category.drop_duplicates()

In [85]:
product_category["product_category_name"] = product_category["product_category_name"].str.strip().str.lower()

In [86]:
product_category["product_category_name_english"] = product_category["product_category_name_english"].str.strip().str.lower()

In [87]:
product_category.groupby("product_category_name").nunique()

                           product_category_name_english
product_category_name
agro_industria_e_comercio                              1
alimentos                                              1
alimentos_bebidas                                      1
artes                                                  1
artes_e_artesanato                                     1
...                                                  ...
sinalizacao_e_seguranca                                1
tablets_impressao_imagem                               1
telefonia                                              1
telefonia_fixa                                         1
utilidades_domesticas                                  1

[71 rows x 1 columns]

In [88]:
product_category.shape # final shape check.

(71, 2)

In [89]:
product_category.to_csv("clean_product_category_name_translation.csv")

In [90]:
# OLIST_GEOLOCATION TABLE CLEANING -->

In [91]:
import pandas as pd
import numpy as np

In [92]:
geolocation = pd.read_csv("olist_geolocation_dataset.csv")

In [93]:
geolocation.shape

(1000163, 5)

In [94]:
geolocation.describe()

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                 1.000163e+06     1.000163e+06     1.000163e+06
mean                  3.657417e+04    -2.117615e+01    -4.639054e+01
std                   3.054934e+04     5.715866e+00     4.269748e+00
min                   1.001000e+03    -3.660537e+01    -1.014668e+02
25%                   1.107500e+04    -2.360355e+01    -4.857317e+01
50%                   2.653000e+04    -2.291938e+01    -4.663788e+01
75%                   6.350400e+04    -1.997962e+01    -4.376771e+01
max                   9.999000e+04     4.506593e+01     1.211054e+02

In [95]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [96]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [98]:
geolocation.duplicated().sum()

np.int64(261831)

In [99]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [100]:
geolocation = geolocation.dropna()

In [101]:
geolocation["geolocation_city"] = (
    geolocation["geolocation_city"]
    .str.strip()
    .str.lower()
)

geolocation["geolocation_state"] = (
    geolocation["geolocation_state"]
    .str.strip()
    .str.upper()
)

In [103]:
# taking average latitude and longitude per ZIP
geolocation_clean = (
    geolocation
    .groupby(
        ["geolocation_zip_code_prefix", "geolocation_city", "geolocation_state"],
        as_index=False
    )
    .agg({
        "geolocation_lat": "mean",
        "geolocation_lng": "mean"
    })
)

In [104]:
geolocation_clean.shape

(27911, 5)

In [105]:
geolocation_clean.head()

,geolocation_zip_code_prefix,geolocation_city,geolocation_state,geolocation_lat,geolocation_lng
0,1001,sao paulo,SP,-23.550215,-46.634019
1,1001,são paulo,SP,-23.549998,-46.634060
2,1002,sao paulo,SP,-23.548438,-46.635129
3,1002,são paulo,SP,-23.544641,-46.633180
4,1003,sao paulo,SP,-23.548988,-46.635786

In [106]:
geolocation_clean.rename(columns={
    "geolocation_zip_code_prefix": "zip_code",
    "geolocation_lat": "latitude",
    "geolocation_lng": "longitude",
    "geolocation_city": "city",
    "geolocation_state": "state"
}, inplace=True)

In [107]:
geolocation_clean.to_csv(
    "clean_olist_geolocation.csv",
    index=False
)