In [4]:
# LEVEL-2 CLEANING  AND MERGING

In [5]:
import pandas as pd
import numpy as np

In [6]:
orders = pd.read_csv("clean_olist_orders.csv", parse_dates=[
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
])

customers = pd.read_csv("clean_olist_customers.csv")
order_items = pd.read_csv("clean_olist_order_items.csv")
payments = pd.read_csv("clean_olist_order_payments.csv")
products = pd.read_csv("clean_olist_products.csv")
reviews = pd.read_csv("clean_olist_order_reviews.csv")
sellers = pd.read_csv("clean_olist_sellers.csv")
category_translation = pd.read_csv("clean_product_category_name_translation.csv")

In [7]:
print(orders.shape)
print(customers.shape)
print(order_items.shape)
print(payments.shape)
print(products.shape)
print(reviews.shape)
print(sellers.shape)
print(category_translation.shape)

(96478, 9)
(99441, 5)
(112650, 8)
(103886, 6)
(32951, 9)
(98410, 7)
(3095, 4)
(71, 3)

In [8]:
# orders table + customers table (base table = orders).
orders_customers = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

In [9]:
# orders table + payments table (base table = orders).
orders_payments = orders_customers.merge(
    payments,
    on="order_id",
    how="left"
)

In [10]:
# orders table + order_items table (base table = orders).
orders_items = orders_payments.merge(
    order_items,
    on="order_id",
    how="left"
)

In [11]:
# orders table + order_products table (base table = orders).
orders_products = orders_items.merge(
    products,
    on="product_id",
    how="left"
)

In [12]:
# adding product_category table.
orders_products = orders_products.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

In [13]:
# adding order_reviews table.
orders_reviews = orders_products.merge(
    reviews,
    on="order_id",
    how="left"
)

In [14]:
# adding order_sellers table (which is a last table) and now, we'll make final dataset table -->
final_df = orders_reviews.merge(
    sellers,
    on="seller_id",
    how="left"
)

In [15]:
final_df.shape

(115361, 44)

In [16]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115361 entries, 0 to 115360
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115361 non-null  object
 1   customer_id                    115361 non-null  object
 2   order_status                   115361 non-null  object
 3   order_purchase_timestamp       115361 non-null  datetime64[ns]
 4   order_approved_at              115346 non-null  datetime64[ns]
 5   order_delivered_carrier_date   115359 non-null  datetime64[ns]
 6   order_delivered_customer_date  115353 non-null  datetime64[ns]
 7   order_estimated_delivery_date  115361 non-null  datetime64[ns]
 8   delivery_delay_days            115353 non-null  float64
 9   customer_unique_id             115361 non-null  object
 10  customer_zip_code_prefix       115361 non-null  int64
 11  customer_city                  115361 non-null  object
 12  customer_state                 115361 non-null  object
 13  payment_sequential             115358 non-null  float64
 14  payment_type                   115358 non-null  object
 15  payment_installments           115358 non-null  float64
 16  payment_value                  115358 non-null  float64
 17  is_installment                 115358 non-null  object
 18  order_item_id                  115361 non-null  int64
 19  product_id                     115361 non-null  object
 20  seller_id                      115361 non-null  object
 21  shipping_limit_date            115361 non-null  object
 22  price                          115361 non-null  float64
 23  freight_value                  115361 non-null  float64
 24  item_total_value               115361 non-null  float64
 25  product_category_name          113725 non-null  object
 26  product_name_lenght            113725 non-null  float64
 27  product_description_lenght     113725 non-null  float64
 28  product_photos_qty             113725 non-null  float64
 29  product_weight_g               115341 non-null  float64
 30  product_length_cm              115341 non-null  float64
 31  product_height_cm              115341 non-null  float64
 32  product_width_cm               115341 non-null  float64
 33  Unnamed: 0                     113702 non-null  float64
 34  product_category_name_english  113702 non-null  object
 35  review_id                      113946 non-null  object
 36  review_score                   113946 non-null  float64
 37  review_comment_title           13542 non-null   object
 38  review_comment_message         47743 non-null   object
 39  review_creation_date           113946 non-null  object
 40  review_answer_timestamp        113946 non-null  object
 41  seller_zip_code_prefix         73802 non-null   float64
 42  seller_city                    115361 non-null  object
 43  seller_state                   115361 non-null  object
dtypes: datetime64[ns](5), float64(17), int64(2), object(20)
memory usage: 38.7+ MB

In [17]:
final_df.describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,customer_zip_code_prefix,payment_sequential,payment_installments,payment_value,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,Unnamed: 0,review_score,seller_zip_code_prefix
count,115361,115346,115359,115353,115361,115353.000000,115361.000000,115358.000000,115358.000000,115358.000000,...,113725.000000,113725.000000,113725.000000,115341.000000,115341.000000,115341.000000,115341.000000,113702.000000,113946.000000,73802.000000
mean,2017-12-31 15:11:11.753755392,2018-01-01 02:36:39.884209152,2018-01-03 22:04:33.601062656,2018-01-13 02:40:35.687567616,2018-01-24 11:08:25.699500032,-12.042383,35071.948709,1.091238,2.939571,171.904259,...,48.802717,785.213392,2.207773,2106.930710,30.237695,16.586270,23.063065,11.436984,4.082653,35291.513333
min,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-10-04 00:00:00,-147.000000,1003.000000,1.000000,0.000000,0.000000,...,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000,0.000000,1.000000,11010.000000
25%,2017-09-12 21:42:52,2017-09-13 13:34:14.249999872,2017-09-15 16:14:38,2017-09-23 16:26:23,2017-10-04 00:00:00,-17.000000,11310.000000,1.000000,1.000000,60.850000,...,42.000000,346.000000,1.000000,300.000000,18.000000,8.000000,15.000000,3.000000,4.000000,14050.000000
50%,2018-01-19 07:31:59,2018-01-19 15:06:14,2018-01-23 19:33:38,2018-02-01 17:35:42,2018-02-15 00:00:00,-13.000000,24315.000000,1.000000,2.000000,108.155000,...,52.000000,601.000000,1.000000,700.000000,25.000000,13.000000,20.000000,7.000000,5.000000,17500.000000
75%,2018-05-04 14:22:16,2018-05-04 21:35:16.249999872,2018-05-08 08:40:00,2018-05-15 14:26:52,2018-05-25 00:00:00,-7.000000,58770.000000,1.000000,4.000000,188.940000,...,57.000000,985.000000,3.000000,1800.000000,38.000000,20.000000,30.000000,16.000000,5.000000,45810.000000
max,2018-08-29 15:00:37,2018-08-29 15:10:26,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-10-25 00:00:00,188.000000,99980.000000,26.000000,24.000000,13664.080000,...,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000,70.000000,5.000000,99730.000000
std,NaN,NaN,NaN,NaN,NaN,10.163687,29851.104796,0.686885,2.775070,265.958525,...,10.018141,650.560111,1.719127,3773.773575,16.127187,13.425326,11.730520,12.418032,1.345966,29324.348510

In [18]:
final_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,customer_unique_id,...,product_category_name_english,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,7c396fd4830fd04220f754e42b4e5bff,...,housewares,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:00,NaN,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,7c396fd4830fd04220f754e42b4e5bff,...,housewares,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:00,NaN,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,7c396fd4830fd04220f754e42b4e5bff,...,housewares,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:00,NaN,maua,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,af07308b275d755c9edb36a90c618231,...,perfumery,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:00,31570.0,belo horizonte,SP
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,3a653a41f6f9fc3d2a113cf8398680e8,...,auto,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:00,14840.0,guariba,SP

In [19]:
# LEVEL-2 OFFICIAL CLEANING AFTER JOINING/ MERGIING TABLES.

In [20]:
# removing logical inconsistencies.
final_df = final_df[
    final_df["order_delivered_customer_date"]
    >= final_df["order_purchase_timestamp"]
]

In [21]:
# handle NULLs created by joins.
final_df["review_score"] = final_df["review_score"].fillna(0)
final_df["payment_value"] = final_df["payment_value"].fillna(0)

In [22]:
# feature engineering.
final_df["delivery_days"] = (
    final_df["order_delivered_customer_date"]
    - final_df["order_purchase_timestamp"]
).dt.days

final_df["delay_flag"] = (
    final_df["order_delivered_customer_date"]
    > final_df["order_estimated_delivery_date"]
)

In [23]:
final_df.shape
final_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,customer_unique_id,...,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,seller_zip_code_prefix,seller_city,seller_state,delivery_days,delay_flag
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,7c396fd4830fd04220f754e42b4e5bff,...,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:00,NaN,maua,SP,8,False
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,7c396fd4830fd04220f754e42b4e5bff,...,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:00,NaN,maua,SP,8,False
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,7c396fd4830fd04220f754e42b4e5bff,...,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:00,NaN,maua,SP,8,False
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,af07308b275d755c9edb36a90c618231,...,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:00,31570.0,belo horizonte,SP,13,False
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,3a653a41f6f9fc3d2a113cf8398680e8,...,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:00,14840.0,guariba,SP,9,False

In [24]:
final_df.to_csv("olist_master_cleaned.csv", index=False)

In [25]:
final_df.shape
final_df.isna().sum().sort_values(ascending=False).head(10)

review_comment_title             101815
review_comment_message            67615
seller_zip_code_prefix            41555
Unnamed: 0                         1659
product_category_name_english      1659
product_name_lenght                1636
product_description_lenght         1636
product_photos_qty                 1636
product_category_name              1636
review_id                          1415
dtype: int64